---
title: "Sediment Quality Objectives: Web tool"
author: ""
output: 
  html_document
self_contained: yes
runtime: shiny
---

```{r, message = F, warning = F, echo = F}
library(knitr)
library(tidyverse)
library(shiny)
opts_chunk$set(warning = FALSE, message = FALSE, eval = T, echo = F)

source('R/funcs.R')

# data inputs
data("indic_lookup")
biota <- read.csv('data/biota.csv', stringsAsFactors = FALSE)
constants <- read.csv('data/constants.csv', stringsAsFactors = FALSE)
contam <- read.csv('data/contamSF.csv', stringsAsFactors = FALSE)
biota_preyprop <- read.csv('data/preyprop.csv', stringsAsFactors = FALSE, row.names = 1)

# indicator species lookup format for inputs
indic_lookup <- indic_lookup %>% 
  group_by(Indicator.number) %>% 
  nest %>% 
  deframe %>% 
  map(function(x) pull(x, Guild.species))
```

# {.tabset}

## Model inputs

```{r}
h3('Indicator guild species')
wellPanel(id = "indicspec", style = "overflow-y:scroll; max-height: 300px; background-color:#daf1da",
  
  # headers
  fluidRow(
    column(4, NULL),
    column(3, 'Select species'), 
    column(4, 'Lipid proportion')
  ),
  
  # indic 1        
  fluidRow(
    column(4, h6('1 Piscivore')),
    column(3, selectInput('indic1', NULL, choices = indic_lookup[['Indicator species 1']])),
    column(2, numericInput('indic1lip', NULL, value = 0.0036, min = 0, max = 1, width = '100%'))
  ),
  
  # indic 2        
  fluidRow(
    column(4, h6('2 Benthic diet with piscivory')),
    column(3, selectInput('indic2', NULL, choices = indic_lookup[['Indicator species 2']])),
    column(2, numericInput('indic2lip', NULL, value = 0.0044, min = 0, max = 1, width = '100%'))
  ),
  
  # indic 3        
  fluidRow(
    column(4, h6('3 Benthic and pelagic with piscivory')),
    column(3, selectInput('indic3', NULL, choices = indic_lookup[['Indicator species 3']])),
    column(2, numericInput('indic3lip', NULL, value = 0.0158, min = 0, max = 1, width = '100%'))
  ),

  # indic 4        
  fluidRow(
    column(4, h6('4 Benthic without piscivory')),
    column(3, selectInput('indic4', NULL, choices = indic_lookup[['Indicator species 4']])),
    column(2, numericInput('indic4lip', NULL, value = 0.0329, min = 0, max = 1, width = '100%'))
  ),

  # indic 5
  fluidRow(
    column(4, h6('5 Benthic and pelagic without piscivory')),
    column(3, selectInput('indic5', NULL, choices = indic_lookup[['Indicator species 5']])),
    column(2, numericInput('indic5lip', NULL, value = 0.0125, min = 0, max = 1, width = '100%'))
  ),

  # indic 6        
  fluidRow(
    column(4, h6('6 Benthic with herbivory')),
    column(3, selectInput('indic6', NULL, choices = indic_lookup[['Indicator species 6']])),
    column(2, numericInput('indic6lip', NULL, value = 0.0356, min = 0, max = 1, width = '100%'))
  ),

  # indic 7        
  fluidRow(
    column(4, h6('7 Benthic and pelagic with herbivory')),
    column(3, selectInput('indic7', NULL, choices = indic_lookup[['Indicator species 7']])),
    column(2, numericInput('indic7lip', NULL, value = 0.0117, min = 0, max = 1, width = '100%'))
  ),

  # indic 8        
  fluidRow(
    column(4, h6('8 Pelagic with benthic herbivory')),
    column(3, selectInput('indic8', NULL, choices = indic_lookup[['Indicator species 8']])),
    column(2, numericInput('indic8lip', NULL, value = 0.0444, min = 0, max = 1, width = '100%'))
  ),

  # indic 9        
  fluidRow(
    column(4, h6('9 Benthic diet with piscivory: estuarine')),
    column(3, selectInput('indic9', NULL, choices = indic_lookup[['Indicator species 9']])),
    column(2, numericInput('indic9lip', NULL, value = 0.0036, min = 0, max = 1, width = '100%'))
  )

)

h3('Environmental data')
wellPanel(id = "envdat", style = "overflow-y:scroll; max-height: 300px; background-color:#daf1da",
    
  # dissolved oxygen       
  fluidRow(
    column(4, h6('Dissolved oxygen (mg/L)')),
    column(2, numericInput('Cox', NULL, value = 8.09, min = 0, width = '100%'))
  ),
  
  # water temp     
  fluidRow(
    column(4, HTML('<h6>Mean water temperature (&deg;C)</h6>')),
    column(2, numericInput('T', NULL, value = 14.9, width = '100%'))
  ), 
  
  # salinity     
  fluidRow(
    column(4, h6('Water salinity (psu)')),
    column(2, numericInput('salinity', NULL, value = 20.2, min = 0, width = '100%'))
  ),
    
  # molar conc seawater       
  fluidRow(
    column(4, h6('Molar conc. seawater at 35 ppt (mol/L)')),
    column(2, numericInput('MCS', NULL, value = 0.5, min = 0, width = '100%'))
  ),   
  
  # organic carb prop in sed      
  fluidRow(
    column(4, h6('Organic carbon in sediment (kg/kg)')),
    column(2, numericInput('ocsed', NULL, value = 0.0102, width = '100%'))
  ),   
  
  # concentration of suspended solids      
  fluidRow(
    column(4, h6('Conc. of suspended solids (kg/L)')),
    column(2, numericInput('vss', NULL, value = 0.0000246, min = 0, width = '100%'))
  ),  
  
  # poc conc in water       
  fluidRow(
    column(4, h6('POC conc. in water (kg/L)')),
    column(2, numericInput('xpoc', NULL, value = 0.00000185, min = 0, width = '100%'))
  ),
  
  # doc conc in water       
  fluidRow(
    column(4, h6('DOC conc. in water (kg/L)')),
    column(2, numericInput('xdoc', NULL, value = 0.0000021, min = 0, width = '100%'))
  )
  
)


h3('Contaminants')
wellPanel(id = "contamdat", style = "overflow-y:scroll; max-height: 300px; background-color:#daf1da",

  # headers
  fluidRow(
    column(2, NULL),
    column(2, NULL),
    column(2, 'Sediment (ng/g dry wt)'), 
    column(2, 'Surface water (pg/L in unfiltered sample)'),
    column(2, 'Dissolved surface water (pg/L)'),
    column(2, 'Pore water (pg/L)')
  ),          

  # Chlordane
  fluidRow(
  	column(2, h6('Chlordane')),
  	column(2, h6('alphaChlordane')),
  	column(2, numericInput('alphaChlordane_sed', NULL, value = 0.5, min = 0, width = '100%')),
  	column(2, numericInput('alphaChlordane_sur', NULL, value = 0.32, min = 0, width = '100%')),
  	column(2, numericInput('alphaChlordane_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('alphaChlordane_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # Chlordane
  fluidRow(
  	column(2, h6('Chlordane')),
  	column(2, h6('gammaChlordane')),
  	column(2, numericInput('gammaChlordane_sed', NULL, value = 0.5, min = 0, width = '100%')),
  	column(2, numericInput('gammaChlordane_sur', NULL, value = 0.16, min = 0, width = '100%')),
  	column(2, numericInput('gammaChlordane_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('gammaChlordane_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # Chlordane
  fluidRow(
  	column(2, h6('Chlordane')),
  	column(2, h6('alphaNonachlor')),
  	column(2, numericInput('alphaNonachlor_sed', NULL, value = 0.49, min = 0, width = '100%')),
  	column(2, numericInput('alphaNonachlor_sur', NULL, value = 0.28, min = 0, width = '100%')),
  	column(2, numericInput('alphaNonachlor_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('alphaNonachlor_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # Chlordane
  fluidRow(
  	column(2, h6('Chlordane')),
  	column(2, h6('gammaNonachlor')),
  	column(2, numericInput('gammaNonachlor_sed', NULL, value = 0.5, min = 0, width = '100%')),
  	column(2, numericInput('gammaNonachlor_sur', NULL, value = 0.05, min = 0, width = '100%')),
  	column(2, numericInput('gammaNonachlor_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('gammaNonachlor_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # Chlordane
  fluidRow(
  	column(2, h6('Chlordane')),
  	column(2, h6('Oxychlordane')),
  	column(2, numericInput('Oxychlordane_sed', NULL, value = 0.23, min = 0, width = '100%')),
  	column(2, numericInput('Oxychlordane_sur', NULL, value = 0.09, min = 0, width = '100%')),
  	column(2, numericInput('Oxychlordane_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('Oxychlordane_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # Dieldrin
  fluidRow(
  	column(2, h6('Dieldrin')),
  	column(2, h6('Dieldrin')),
  	column(2, numericInput('Dieldrin_sed', NULL, value = 0.5, min = 0, width = '100%')),
  	column(2, numericInput('Dieldrin_sur', NULL, value = 0.23, min = 0, width = '100%')),
  	column(2, numericInput('Dieldrin_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('Dieldrin_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # DDT
  fluidRow(
  	column(2, h6('DDT')),
  	column(2, h6('op-DDD')),
  	column(2, numericInput('op-DDD_sed', NULL, value = 0.189302326, min = 0, width = '100%')),
  	column(2, numericInput('op-DDD_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('op-DDD_dis', NULL, value = 9.305665792, min = 0, width = '100%')),
  	column(2, numericInput('op-DDD_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # DDT
  fluidRow(
  	column(2, h6('DDT')),
  	column(2, h6('op-DDE')),
  	column(2, numericInput('op-DDE_sed', NULL, value = 6.704795349, min = 0, width = '100%')),
  	column(2, numericInput('op-DDE_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('op-DDE_dis', NULL, value = 44.88585023, min = 0, width = '100%')),
  	column(2, numericInput('op-DDE_por', NULL, value = 63.87, min = 0, width = '100%'))
  	),
  
  # DDT
  fluidRow(
  	column(2, h6('DDT')),
  	column(2, h6('op-DDT')),
  	column(2, numericInput('op-DDT_sed', NULL, value = 1.2, min = 0, width = '100%')),
  	column(2, numericInput('op-DDT_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('op-DDT_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('op-DDT_por', NULL, value = 15.68, min = 0, width = '100%'))
  	),
  
  # DDT
  fluidRow(
  	column(2, h6('DDT')),
  	column(2, h6('pp-DDD')),
  	column(2, numericInput('pp-DDD_sed', NULL, value = 3.243651395, min = 0, width = '100%')),
  	column(2, numericInput('pp-DDD_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('pp-DDD_dis', NULL, value = 19.45333669, min = 0, width = '100%')),
  	column(2, numericInput('pp-DDD_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # DDT
  fluidRow(
  	column(2, h6('DDT')),
  	column(2, h6('pp-DDE')),
  	column(2, numericInput('pp-DDE_sed', NULL, value = 44.74623256, min = 0, width = '100%')),
  	column(2, numericInput('pp-DDE_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('pp-DDE_dis', NULL, value = 306.1044638, min = 0, width = '100%')),
  	column(2, numericInput('pp-DDE_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # DDT
  fluidRow(
  	column(2, h6('DDT')),
  	column(2, h6('pp-DDT')),
  	column(2, numericInput('pp-DDT_sed', NULL, value = 1.099302326, min = 0, width = '100%')),
  	column(2, numericInput('pp-DDT_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('pp-DDT_dis', NULL, value = 8.092710587, min = 0, width = '100%')),
  	column(2, numericInput('pp-DDT_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 8')),
  	column(2, numericInput('PCB 8_sed', NULL, value = 0.5, min = 0, width = '100%')),
  	column(2, numericInput('PCB 8_sur', NULL, value = 16.84, min = 0, width = '100%')),
  	column(2, numericInput('PCB 8_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 8_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 11')),
  	column(2, numericInput('PCB 11_sed', NULL, value = 0.36, min = 0, width = '100%')),
  	column(2, numericInput('PCB 11_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 11_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 11_por', NULL, value = 47.65, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 18')),
  	column(2, numericInput('PCB 18_sed', NULL, value = 0.101054884, min = 0, width = '100%')),
  	column(2, numericInput('PCB 18_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 18_dis', NULL, value = 13.185837, min = 0, width = '100%')),
  	column(2, numericInput('PCB 18_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 27')),
  	column(2, numericInput('PCB 27_sed', NULL, value = 0.44, min = 0, width = '100%')),
  	column(2, numericInput('PCB 27_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 27_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 27_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 28')),
  	column(2, numericInput('PCB 28_sed', NULL, value = 0.166863488, min = 0, width = '100%')),
  	column(2, numericInput('PCB 28_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 28_dis', NULL, value = 11.43476661, min = 0, width = '100%')),
  	column(2, numericInput('PCB 28_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 29')),
  	column(2, numericInput('PCB 29_sed', NULL, value = 0.72, min = 0, width = '100%')),
  	column(2, numericInput('PCB 29_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 29_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 29_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 31')),
  	column(2, numericInput('PCB 31_sed', NULL, value = 0.13606575, min = 0, width = '100%')),
  	column(2, numericInput('PCB 31_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 31_dis', NULL, value = 6.363272245, min = 0, width = '100%')),
  	column(2, numericInput('PCB 31_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 33')),
  	column(2, numericInput('PCB 33_sed', NULL, value = 0.36, min = 0, width = '100%')),
  	column(2, numericInput('PCB 33_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 33_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 33_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 37')),
  	column(2, numericInput('PCB 37_sed', NULL, value = 0.42, min = 0, width = '100%')),
  	column(2, numericInput('PCB 37_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 37_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 37_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 44')),
  	column(2, numericInput('PCB 44_sed', NULL, value = 0.405351163, min = 0, width = '100%')),
  	column(2, numericInput('PCB 44_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 44_dis', NULL, value = 16.2247466, min = 0, width = '100%')),
  	column(2, numericInput('PCB 44_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 49')),
  	column(2, numericInput('PCB 49_sed', NULL, value = 0.5, min = 0, width = '100%')),
  	column(2, numericInput('PCB 49_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 49_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 49_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 52')),
  	column(2, numericInput('PCB 52_sed', NULL, value = 0.5, min = 0, width = '100%')),
  	column(2, numericInput('PCB 52_sur', NULL, value = 27.86, min = 0, width = '100%')),
  	column(2, numericInput('PCB 52_dis', NULL, value = 17.33, min = 0, width = '100%')),
  	column(2, numericInput('PCB 52_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 56')),
  	column(2, numericInput('PCB 56_sed', NULL, value = 0.54, min = 0, width = '100%')),
  	column(2, numericInput('PCB 56_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 56_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 56_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 60')),
  	column(2, numericInput('PCB 60_sed', NULL, value = 0.61, min = 0, width = '100%')),
  	column(2, numericInput('PCB 60_sur', NULL, value = 120.4, min = 0, width = '100%')),
  	column(2, numericInput('PCB 60_dis', NULL, value = 65.32, min = 0, width = '100%')),
  	column(2, numericInput('PCB 60_por', NULL, value = 140.8, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 64')),
  	column(2, numericInput('PCB 64_sed', NULL, value = 0.38, min = 0, width = '100%')),
  	column(2, numericInput('PCB 64_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 64_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 64_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 66')),
  	column(2, numericInput('PCB 66_sed', NULL, value = 1.05, min = 0, width = '100%')),
  	column(2, numericInput('PCB 66_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 66_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 66_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 70')),
  	column(2, numericInput('PCB 70_sed', NULL, value = 1.35, min = 0, width = '100%')),
  	column(2, numericInput('PCB 70_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 70_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 70_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 74')),
  	column(2, numericInput('PCB 74_sed', NULL, value = 0.194457209, min = 0, width = '100%')),
  	column(2, numericInput('PCB 74_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 74_dis', NULL, value = 3.470400349, min = 0, width = '100%')),
  	column(2, numericInput('PCB 74_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 77')),
  	column(2, numericInput('PCB 77_sed', NULL, value = 1.12, min = 0, width = '100%')),
  	column(2, numericInput('PCB 77_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 77_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 77_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 81')),
  	column(2, numericInput('PCB 81_sed', NULL, value = 1.09, min = 0, width = '100%')),
  	column(2, numericInput('PCB 81_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 81_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 81_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 87')),
  	column(2, numericInput('PCB 87_sed', NULL, value = 1.4, min = 0, width = '100%')),
  	column(2, numericInput('PCB 87_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 87_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 87_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 95')),
  	column(2, numericInput('PCB 95_sed', NULL, value = 0.77, min = 0, width = '100%')),
  	column(2, numericInput('PCB 95_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 95_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 95_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 97')),
  	column(2, numericInput('PCB 97_sed', NULL, value = 0.3636925, min = 0, width = '100%')),
  	column(2, numericInput('PCB 97_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 97_dis', NULL, value = 3.681928399, min = 0, width = '100%')),
  	column(2, numericInput('PCB 97_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 99')),
  	column(2, numericInput('PCB 99_sed', NULL, value = 0.617086047, min = 0, width = '100%')),
  	column(2, numericInput('PCB 99_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 99_dis', NULL, value = 5.897746631, min = 0, width = '100%')),
  	column(2, numericInput('PCB 99_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 101')),
  	column(2, numericInput('PCB 101_sed', NULL, value = 0.181250006, min = 0, width = '100%')),
  	column(2, numericInput('PCB 101_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 101_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 101_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 105')),
  	column(2, numericInput('PCB 105_sed', NULL, value = 0.454006977, min = 0, width = '100%')),
  	column(2, numericInput('PCB 105_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 105_dis', NULL, value = 1.599129689, min = 0, width = '100%')),
  	column(2, numericInput('PCB 105_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 110')),
  	column(2, numericInput('PCB 110_sed', NULL, value = 1.601034884, min = 0, width = '100%')),
  	column(2, numericInput('PCB 110_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 110_dis', NULL, value = 9.244741774, min = 0, width = '100%')),
  	column(2, numericInput('PCB 110_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 114')),
  	column(2, numericInput('PCB 114_sed', NULL, value = 0.33, min = 0, width = '100%')),
  	column(2, numericInput('PCB 114_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 114_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 114_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 118')),
  	column(2, numericInput('PCB 118_sed', NULL, value = 0.275000006, min = 0, width = '100%')),
  	column(2, numericInput('PCB 118_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 118_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 118_por', NULL, value = 17.98, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 119')),
  	column(2, numericInput('PCB 119_sed', NULL, value = 0.41, min = 0, width = '100%')),
  	column(2, numericInput('PCB 119_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 119_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 119_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 123')),
  	column(2, numericInput('PCB 123_sed', NULL, value = 0.63, min = 0, width = '100%')),
  	column(2, numericInput('PCB 123_sur', NULL, value = 56.74, min = 0, width = '100%')),
  	column(2, numericInput('PCB 123_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 123_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 126')),
  	column(2, numericInput('PCB 126_sed', NULL, value = 0.38, min = 0, width = '100%')),
  	column(2, numericInput('PCB 126_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 126_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 126_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 128')),
  	column(2, numericInput('PCB 128_sed', NULL, value = 0.71, min = 0, width = '100%')),
  	column(2, numericInput('PCB 128_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 128_dis', NULL, value = 96.32, min = 0, width = '100%')),
  	column(2, numericInput('PCB 128_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 132')),
  	column(2, numericInput('PCB 132_sed', NULL, value = 0.33, min = 0, width = '100%')),
  	column(2, numericInput('PCB 132_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 132_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 132_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 137')),
  	column(2, numericInput('PCB 137_sed', NULL, value = 0.56, min = 0, width = '100%')),
  	column(2, numericInput('PCB 137_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 137_dis', NULL, value = 165.6, min = 0, width = '100%')),
  	column(2, numericInput('PCB 137_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 138')),
  	column(2, numericInput('PCB 138_sed', NULL, value = 0.25384615, min = 0, width = '100%')),
  	column(2, numericInput('PCB 138_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 138_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 138_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 141')),
  	column(2, numericInput('PCB 141_sed', NULL, value = 0.29, min = 0, width = '100%')),
  	column(2, numericInput('PCB 141_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 141_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 141_por', NULL, value = 27.86, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 146')),
  	column(2, numericInput('PCB 146_sed', NULL, value = 1.01, min = 0, width = '100%')),
  	column(2, numericInput('PCB 146_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 146_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 146_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 149')),
  	column(2, numericInput('PCB 149_sed', NULL, value = 1.25, min = 0, width = '100%')),
  	column(2, numericInput('PCB 149_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 149_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 149_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 151')),
  	column(2, numericInput('PCB 151_sed', NULL, value = 0.215226512, min = 0, width = '100%')),
  	column(2, numericInput('PCB 151_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 151_dis', NULL, value = 1.879261719, min = 0, width = '100%')),
  	column(2, numericInput('PCB 151_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 153')),
  	column(2, numericInput('PCB 153_sed', NULL, value = 1.39244, min = 0, width = '100%')),
  	column(2, numericInput('PCB 153_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 153_dis', NULL, value = 5.251926401, min = 0, width = '100%')),
  	column(2, numericInput('PCB 153_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 156')),
  	column(2, numericInput('PCB 156_sed', NULL, value = 0.148466047, min = 0, width = '100%')),
  	column(2, numericInput('PCB 156_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 156_dis', NULL, value = 0.319787514, min = 0, width = '100%')),
  	column(2, numericInput('PCB 156_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 157')),
  	column(2, numericInput('PCB 157_sed', NULL, value = 0.56, min = 0, width = '100%')),
  	column(2, numericInput('PCB 157_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 157_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 157_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 158')),
  	column(2, numericInput('PCB 158_sed', NULL, value = 1.3, min = 0, width = '100%')),
  	column(2, numericInput('PCB 158_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 158_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 158_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 167')),
  	column(2, numericInput('PCB 167_sed', NULL, value = 0.74, min = 0, width = '100%')),
  	column(2, numericInput('PCB 167_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 167_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 167_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 168')),
  	column(2, numericInput('PCB 168_sed', NULL, value = 0.21, min = 0, width = '100%')),
  	column(2, numericInput('PCB 168_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 168_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 168_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 169')),
  	column(2, numericInput('PCB 169_sed', NULL, value = 1.11, min = 0, width = '100%')),
  	column(2, numericInput('PCB 169_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 169_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 169_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 170')),
  	column(2, numericInput('PCB 170_sed', NULL, value = 0.330709302, min = 0, width = '100%')),
  	column(2, numericInput('PCB 170_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 170_dis', NULL, value = 0.569421342, min = 0, width = '100%')),
  	column(2, numericInput('PCB 170_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 174')),
  	column(2, numericInput('PCB 174_sed', NULL, value = 0.322745, min = 0, width = '100%')),
  	column(2, numericInput('PCB 174_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 174_dis', NULL, value = 0.894510598, min = 0, width = '100%')),
  	column(2, numericInput('PCB 174_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 177')),
  	column(2, numericInput('PCB 177_sed', NULL, value = 0.121874884, min = 0, width = '100%')),
  	column(2, numericInput('PCB 177_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 177_dis', NULL, value = 0.522629476, min = 0, width = '100%')),
  	column(2, numericInput('PCB 177_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 180')),
  	column(2, numericInput('PCB 180_sed', NULL, value = 0.697543256, min = 0, width = '100%')),
  	column(2, numericInput('PCB 180_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 180_dis', NULL, value = 1.495032452, min = 0, width = '100%')),
  	column(2, numericInput('PCB 180_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 183')),
  	column(2, numericInput('PCB 183_sed', NULL, value = 0.112256047, min = 0, width = '100%')),
  	column(2, numericInput('PCB 183_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 183_dis', NULL, value = 0.451321306, min = 0, width = '100%')),
  	column(2, numericInput('PCB 183_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 187')),
  	column(2, numericInput('PCB 187_sed', NULL, value = 0.7125, min = 0, width = '100%')),
  	column(2, numericInput('PCB 187_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 187_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 187_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 189')),
  	column(2, numericInput('PCB 189_sed', NULL, value = 0.64, min = 0, width = '100%')),
  	column(2, numericInput('PCB 189_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 189_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 189_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 194')),
  	column(2, numericInput('PCB 194_sed', NULL, value = 0.19812907, min = 0, width = '100%')),
  	column(2, numericInput('PCB 194_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 194_dis', NULL, value = 0.238347374, min = 0, width = '100%')),
  	column(2, numericInput('PCB 194_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 195')),
  	column(2, numericInput('PCB 195_sed', NULL, value = 0.066266, min = 0, width = '100%')),
  	column(2, numericInput('PCB 195_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 195_dis', NULL, value = 0.10184514, min = 0, width = '100%')),
  	column(2, numericInput('PCB 195_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 198')),
  	column(2, numericInput('PCB 198_sed', NULL, value = 0.45, min = 0, width = '100%')),
  	column(2, numericInput('PCB 198_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 198_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 198_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 199')),
  	column(2, numericInput('PCB 199_sed', NULL, value = 0.68, min = 0, width = '100%')),
  	column(2, numericInput('PCB 199_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 199_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 199_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 200')),
  	column(2, numericInput('PCB 200_sed', NULL, value = 0.77, min = 0, width = '100%')),
  	column(2, numericInput('PCB 200_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 200_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 200_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 201')),
  	column(2, numericInput('PCB 201_sed', NULL, value = 0.015007186, min = 0, width = '100%')),
  	column(2, numericInput('PCB 201_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 201_dis', NULL, value = 0.04712185, min = 0, width = '100%')),
  	column(2, numericInput('PCB 201_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 203')),
  	column(2, numericInput('PCB 203_sed', NULL, value = 1.15, min = 0, width = '100%')),
  	column(2, numericInput('PCB 203_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 203_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 203_por', NULL, value = NULL, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 206')),
  	column(2, numericInput('PCB 206_sed', NULL, value = 1.02, min = 0, width = '100%')),
  	column(2, numericInput('PCB 206_sur', NULL, value = 117.8, min = 0, width = '100%')),
  	column(2, numericInput('PCB 206_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 206_por', NULL, value = 125.7, min = 0, width = '100%'))
  	),
  
  # PCB
  fluidRow(
  	column(2, h6('PCB')),
  	column(2, h6('PCB 209')),
  	column(2, numericInput('PCB 209_sed', NULL, value = 0.86, min = 0, width = '100%')),
  	column(2, numericInput('PCB 209_sur', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 209_dis', NULL, value = NULL, min = 0, width = '100%')),
  	column(2, numericInput('PCB 209_por', NULL, value = NULL, min = 0, width = '100%'))
  	)

)
```

## Run bioaccumulation model

```{r}
actionButton("run", "Run!")

bsaf_res <- eventReactive(input$run, {
  
  # format biota from input
  biota <- formsppinp(input, biota)

  # format constants forminput
  constants <- formcnsinp(input, constants)
  
  res <- bioaccum_batch(biota, contam, biota_preyprop, constants)

  return(res)
  
})

renderUI({
  
  # input
  bsaf_res <- bsaf_res()
  BSAF <- bsaf_res$BSAF
  
  selectInput('cntbsaf', 'Select contaminant:', choices = colnames(BSAF))
  
})

renderPlot({
  
  bsaf_res <- bsaf_res()
  BSAF <- bsaf_res$BSAF
  CBIOTA <- bsaf_res$CBIOTA
  contam <- bsaf_res$contam
  cntbsaf <- input$cntbsaf
  
  req(cntbsaf)
  
  toplo <- BSAF %>% 
    data.frame %>% 
    rownames_to_column('species') %>% 
    select(species, !!cntbsaf)
  
  p <- ggplot(toplo, aes_string(x = 'species', y = cntbsaf)) + 
    geom_bar(stat = 'identity') + 
    ylab('BSAF') + 
    theme_bw(base_size= 16, base_family = 'serif')+ 
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
      axis.title.x = element_blank()
      )
  
  return(p)
  
})


renderUI({
  
  # input
  bsaf_res <- bsaf_res()
  BSAF <- bsaf_res$BSAF
  
  selectInput('sppbsaf', 'Select species:', choices = rownames(BSAF))
  
})

renderPlot({
  
  bsaf_res <- bsaf_res()
  BSAF <- bsaf_res$BSAF
  CBIOTA <- bsaf_res$CBIOTA
  contam <- bsaf_res$contam
  sppbsaf <- input$sppbsaf
  
  req(sppbsaf)
  
  toplo <- BSAF %>% 
    data.frame %>% 
    rownames_to_column('species') %>% 
    filter(species %in% sppbsaf) %>% 
    gather('contam', 'val', -species)
  
  p <- ggplot(toplo, aes_string(x = 'contam', y = 'val')) + 
    geom_bar(stat = 'identity') + 
    ylab('BSAF') + 
    theme_bw(base_size= 16, base_family = 'serif')+ 
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
      axis.title.x = element_blank()
      )
  
  return(p)
  
})

renderPlot({
 
  bsaf_res <- bsaf_res()
  BSAF <- bsaf_res$BSAF
  CBIOTA <- bsaf_res$CBIOTA
  contam <- bsaf_res$contam
  sppbsaf <- input$sppbsaf

  toplo <- BSAF %>% 
    data.frame %>% 
    rownames_to_column('species') %>% 
    filter(species %in% sppbsaf) %>% 
    gather('Chem', 'val', -species) %>%
    mutate(Chem = factor(Chem)) %>% 
    left_join(contam, by = 'Chem')
  
  p <- ggplot(toplo, aes(x = Kow, y = val)) + 
    geom_point() + 
    scale_x_log10('log10 Octanol-water partitioning coeff') + 
    ylab('BSAF') + 
    theme_bw(base_size= 16, base_family = 'serif')
  
  return(p)
  
})
```
